version: '3.9'
services:
    app:
        container_name: clin_plus_api
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - '3000:3000'
        volumes:
            - .:/usr/src/app
        depends_on:
            - database
    database:
        container_name: mysql
        image: mysql:8.0.32
        restart: unless-stopped
        command: ['--default-authentication-plugin=mysql_native_password']
        ports:
            - '3306:3306'
        volumes:
            - clin_plus_db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: '${DATABASE_ROOT_PASSWORD}'
            MYSQL_DATABASE: clinplus
            MYSQL_USER: masteruser
            MYSQL_PASSWORD: '${DATABASE_PASSWORD}'
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        depends_on:
            - database
        environment:
            PMA_HOST: database
            MYSQL_ROOT_PASSWORD: '${DATABASE_ROOT_PASSWORD}'
            UPLOAD_LIMIT: 50M
volumes:
    clin_plus_db_data:
