version: '3.9'
services:
    app:
        container_name: clin_plus_api
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - '3000:3000'
        volumes:
            - .:/usr/src/app
        depends_on:
            - database
    database:
        container_name: mysql
        image: mysql:8.0.32
        restart: unless-stopped
        command:
            [
                '--default-authentication-plugin=mysql_native_password',
                '--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION',
            ]
        ports:
            - '${DATABASE_EXTERNAL_PORT}:3306'
        volumes:
            - clin_plus_db_data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
volumes:
    clin_plus_db_data:
